name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Make sure this is the branch you're working on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    # Set Git identity
    - name: Configure Git user
      run: |
        git config  user.name "Yab112"
        git config  user.email "eshetieyabibal@gmail.com"

    - name: Deploy to GitHub Pages
      run: npm run deploy
