name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: pages-artifact
        path: dist

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: pages-artifact
      